spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/final_project?useSSL=false&serverTimezone=UTC
    username: root
    password:
logging:
  level:
    root: INFO
    sql: DEBUG
    projects.onlineshop: DEBUG


## Konfiguracja bazy danych
#spring.datasource.url=jdbc:mysql://localhost:3306/shop_db
#
## Konfiguracja Hibernate & JPA
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.open-in-view=false
#
## Logowanie
#logging.level.root=WARN

